name: Pre-commit (Prek)
on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v3
        with:
          version: 2026.4.4
      - name: Run pre-commit
        run: |
          prek run \
          --show-diff-on-failure \
          --color always \
          --all-files
